# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944d4e0b6b06de480163cf201c13d80ec7ceb8ed055d879d0241a945b22154d33957bd1e975bc213711230c70f9e90fc13dd3c31effed29e1ddfa8b1b8a52f81

test:
  secret_key_base: c4030295f65f185c3daf7ecd7f986139dcdeebda7f720c13ecb7674d6228ab8e8a935b5758ce82d0f7226ae0161e86f5094aad38f3299e0b6e75bca5b79b9faa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
